name: CI


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Echo start
        run: echo starting

      - name: test print stuff
        run: |
          echo "$INPUT_DOCKER_USER"
          echo "$INPUT_DOCKER_ACCESS_TOKEN"
          echo "${{ INPUT_SERVICE_NAME }}"
          echo "${{ INPUT_ENVS }}"
          echo "${{ INPUT_SSH_HOST }}"
          echo "${{ INPUT_SSH_PASSWORD }}"
          echo "${{ INPUT_SSH_USERNAME }}"
      
      # - name: Execute deployment script
      #   run: |
      #     chmod +x ./deployImage.sh
      #     ./deployImage.sh
      #   shell: bash

      - name: Echo end
        run: echo ending
